# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="agnoster"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
zstyle ':omz:update' frequency 2

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git kubectl history emoji encode64 zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.

# Custom Aliases
alias mefi="~/.MountEFI/MountEFI.command"   # Mount EFI
alias dl="cd ~/Downloads"   # Go to the Downloads folder
alias dc="cd ~/Documents"   # Go to the Documents folder
alias gh="cd ~/Documents/GitHub"   # Go to the Documents folder
alias dt="cd ~/Desktop"   # Go to the Desktop folder
alias ..="cd .."   # Go up one directory
alias ...="cd ../.."   # Go up two directories
alias home="cd ~"   # Go to home directory
alias cp="cp -i"   # Prompt before overwriting files
alias mv="mv -i"   # Prompt before overwriting files
alias rm="rm -i"   # Prompt before deleting files
alias ls="ls -G"   # Colorize the ls command output
alias ll="ls -al"   # List all files with details
alias la="ls -A"   # List all files, including hidden ones
alias gs="git status"   # Show Git status
alias ga="git add"   # Git add
alias gc="git commit -m"   # Git commit with a message
alias gd="git diff"   # Show Git diff
alias glog="git log --oneline --decorate --graph"   # Show a prettier Git log
alias sysinfo="system_profiler SPSoftwareDataType"   # Display system information
alias myip="curl ifconfig.me"   # Get your public IP address
alias pinggoogle="ping -c 4 google.com"   # Ping Google to check network connectivity
alias speedtest="curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -"   # Run a speedtest
alias ghclone="git clone"   # Clone a GitHub repository
alias glclone="git clone"   # Clone a GitLab repository
alias findfile="find . -type f -name"   # Search for files by name in the current directory
alias findtext="grep -r"   # Search for text within files in the current directory and subdirectories
alias back="cd -"   # Quickly switch between the current and previous directory
alias c="clear"   # Clear the terminal screen
alias vscode="open -a 'VSCodium'"
alias nano='/usr/local/bin/nano'
alias lvim="~/.local/bin/lvim"

# Directory Shortcuts
alias projects="cd ~/Projects"
alias work="cd ~/Documents/Work"
alias notes="cd ~/Documents/Notes"

# Git Aliases
alias gaa="git add --all"
alias gp="git pull"
alias gps="git push"
alias gl="git log"
alias gco="git checkout"
alias gcm="git checkout main"
alias grv="git remote -v"


# Docker Shortcuts
alias d="docker"
alias dc="docker-compose"

# SSH Shortcuts
alias winserver="ssh Administrator@Windows-Server"

# Text Editors
alias editfile="code"
alias editconfig="nano ~/.zshrc"

# System Utilities
alias sysinfo="system_profiler SPSoftwareDataType"

# Network Tools
alias myip="curl ifconfig.me"
alias pinggoogle="ping -c 4 google.com"
alias speedtest="curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -"

# Miscellaneous
alias mycustomscript="~/path/to/custom/script.sh"

# Add any other custom aliases or functions below this line

